name: Homes
main: com.guntherdw.bukkit.Homes.Homes
website: https://github.com/GuntherDW/Homes
version: 2.5
authors:
    - Grumm
    - Meaglin
    - GuntherDW
commands:
    homes:
        description: Multi-homes plugin
        usage: /<command> add <alias> | del <alias> | use <alias> | list | tpback
        _permission: homes.homes
    home:
        description: Go to your home
        usage: /<command>
    sethome:
        description: Set your home to your current position
        usage: /<command>
    reloadhomes:
        description: Reloads the homes map
        usage: /<command>
        _permission: homes.homesother